bidder/urls.py
from django.urls import path

from . import views

# pylint: disable=invalid-name
app_name = "bidder"
urlpatterns = [
    path("", views.index, name="index"),
    path("help/", views.help_view, name="help"),
    path("user/", views.user_details, name="user"),
    path("<int:property_id>/", views.detail, name="detail"),
    path("<int:property_id>/bid/", views.bid, name="bid"),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
]

bidsite/urls.py
import os
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

extra_urls = []
if os.getenv("LOCAL_RUN", None):
    extra_urls = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns = [
    path("", RedirectView.as_view(url='/bidder/', permanent=True)),
    path("bidder/", include("bidder.urls")),
    path("admin/", admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + extra_urls

bidder/models.py
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.db import models
from django.utils import timezone

from .services import localization_service
from .services.user_service import BidderUserManager


class Property(models.Model):
    address = models.CharField(max_length=200)
    uploaded_date = models.DateTimeField("date uploaded", default=timezone.now)
    minimum_increment = models.IntegerField(default=500)
    link = models.TextField(blank=True, default="")
    image = models.ImageField(upload_to='property_images/', blank=True)

    class Meta:
        permissions = [
            ('view_bids', 'Can view all bids'),
        ]

    def __str__(self):
        return f"{self.address}"


class BidUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True)
    first_name = models.CharField(max_length=200, blank=True)
    surname = models.CharField(max_length=200, blank=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    viewable_properties = models.ManyToManyField(Property, related_name='viewable_by_users')

    objects = BidderUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return f"{self.email}"


class Bid(models.Model):
    property = models.ForeignKey(Property, on_delete=models.CASCADE)
    user = models.ForeignKey(BidUser, on_delete=models.CASCADE)
    bid = models.IntegerField()
    timestamp = models.DateTimeField("date bid", default=timezone.now)

    def bid_to_str(self):
        return localization_service.format_number_as_pound_value_commas(self.bid)

bidder/forms.py
# pylint: disable=too-many-ancestors
from django import forms
from django.contrib.admin.widgets import FilteredSelectMultiple
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm
from django.contrib.auth import get_user_model

from .models import Property


# Login
class MyLoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'Email Address'
        self.fields['password'].label = 'Password'


class MyUserCreationForm(UserCreationForm):
    viewable_properties = forms.ModelMultipleChoiceField(
        queryset=Property.objects.all(),
        required=False,
        widget=FilteredSelectMultiple(
            verbose_name='Viewable Properties',
            is_stacked=False
        ),
        help_text='Select properties this user can view.'
    )

    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = ('email', 'first_name', 'surname', 'password', 'is_active', 'is_staff', 'viewable_properties')

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super().save(commit=False)
        if commit:
            user.save()
            if self.cleaned_data['viewable_properties']:
                user.viewable_properties.set(self.cleaned_data['viewable_properties'])
        return user


class MyUserChangeForm(UserChangeForm):
    viewable_properties = forms.ModelMultipleChoiceField(
        queryset=Property.objects.all(),
        required=False,
        widget=FilteredSelectMultiple(
            verbose_name='Viewable Properties',
            is_stacked=False
        ),
        help_text='Select properties this user can view.'
    )

    class Meta(UserChangeForm.Meta):
        model = get_user_model()
        fields = ('email', 'first_name', 'surname', 'password', 'is_active', 'is_staff', 'viewable_properties')

bidder/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout

from .services import property_service
from .forms import MyLoginForm


def user_login(request):
    if request.method == 'POST':
        form = MyLoginForm(request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('bidder:index')  # Redirect to a success page.
    else:
        form = MyLoginForm()
    return render(request, 'bidder/login.html', {'form': form})


def user_logout(request):
    logout(request)
    return redirect('bidder:login')  # Redirect to the index page after logout


@login_required
def index(request):
    context = property_service.fetch_property_list_context(request)
    return render(request, "bidder/index.html", context)


@login_required
def detail(request, property_id):
    if property_service.can_view_property(request.user, property_id):
        context = property_service.fetch_property_context(request, property_id, None)
        return render(request, "bidder/detail.html", context)
    return index(request)


@login_required
def bid(request, property_id):
    if property_service.can_view_property(request.user, property_id):
        return property_service.place_bid(request, property_id)
    return index(request)


@login_required
def help_view(request):
    return render(request, "bidder/help.html")


@login_required
def user_details(request):
    return render(request, "bidder/user.html")

bidder/templates/bidder/base.html
{% load static %}  <!-- This line loads the static file handling tags -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bidder</title>
    <link rel="stylesheet" href="{% static 'bidder/style.css' %}">
    <link rel="shortcut icon" href="{% static 'bidder/logo.png' %}" type="image/x-icon">
    <link rel="icon" href="{% static 'bidder/logo.png' %}" type="image/x-icon">
</head>
<body>
    <header>
        <nav class="navbar">
            <a href="{% url 'bidder:index' %}" class="logo-container">
                <img src="{% static 'bidder/logo.png' %}" class="logo-image" alt="logo">
                <div class="logo-text large-font bold">Bidder</div>
            </a>
            <ul class="nav-links">
                <li>
                    <a href="{% url 'bidder:index' %}">
                        <img src="{% static 'bidder/icons/home.svg' %}" alt="Home" class="nav-icon">
                    </a>
                </li>
                {% if user.is_authenticated %}
                <li>
                    <a href="{% url 'bidder:user' %}">
                        <img src="{% static 'bidder/icons/user.svg' %}" alt="User" class="nav-icon">
                    </a>
                </li>
                <li>
                    <a href="{% url 'bidder:help' %}">
                        <img src="{% static 'bidder/icons/help.svg' %}" alt="Help" class="nav-icon">
                    </a>
                </li>
                <li>
                    <a href="{% url 'bidder:logout' %}" method="post" title="Logout">
                        <img src="{% static 'bidder/icons/logout.svg' %}" alt="Logout" class="nav-icon">
                    </a>
                </li>
                {% endif %}
            </ul>
        </nav>
    </header>

    {% block content %}
    <!-- This block will be overridden by child templates -->
    {% endblock %}

    <footer>
        <p class="bold">&copy; 2024 Bidder. All rights reserved.</p>
    </footer>
</body>
</html>

bidder/templates/bidder/detail.html
{% extends "bidder/base.html" %}

{% block content %}
<div class="content-container">
    <div class="property-image-container">
        <div class="property-image">
            <img src="{{ property.image.url }}" alt="{{ property.address }} image">
        </div>
    </div>
    <div class="form-container">
        <h3>{{ property.address }}</h3>
        <a href="{{ property.link }}">Link to Property</a>
        <p class="text-line">Minimum bid increment: {{ minimum_increment }}</p>
        <form id="bidForm" action="{% url 'bidder:bid' property.id %}" method="post" class="small-form">
            {% csrf_token %}
            <fieldset>
                <p class="bold text-line">Top bid: {{ top_bid }}</p>
                <p class="text-line">Your bid: {{ user_bid }}</p>
                <input class="bid-input" type="text" name="bid" id="bid-value" value=" {{ input_bid }}">
                <button type="button" class="submit-btn" onclick="confirmSubmission()">Bid</button>
                {% if error_message %}<p class="error">{{ error_message }}</p>{% endif %}
            </fieldset>
        </form>
    </div>
</div>
<div class="table-container">
    {% if bids_list %}
    <h3>Previous Bids</h3>
    <table>
        <thead>
            <tr>
                <th>Bid</th>
                <th>Bidder</th>
                <th>Date</th>
            </tr>
        </thead>
        <tbody>
            {% for bid in bids_list %}
            <tr>
                <td>{{ bid.bid_to_str }}</td>
                <td>{{ bid.user.first_name }} {{ bid.user.surname }}</td>
                <td>{{ bid.timestamp }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% endif %}
</div>

<script>
function confirmSubmission() {
    var confirmAction = confirm("Are you sure you want to submit this bid?");
    if (confirmAction) {
        document.getElementById('bidForm').submit(); // Submit the form if confirmed
    } else {
        // Do nothing if cancelled
        console.log("Bid submission cancelled.");
    }
}
</script>
{% endblock %}

bidder/templates/bidder/help.html
{% extends "bidder/base.html" %}

{% block content %}

<div class="search-container">
    <h3>Help section coming soon... 🔨</h3>
</div>

{% endblock %}

bidder/templates/bidder/index.html
{% extends "bidder/base.html" %}

{% block content %}
{% if user.is_staff %}
    <!-- Search bar container -->
    <div class="search-container">
        <form action="{% url 'bidder:index' %}" method="get">
            <div class="search-wrapper">
                <input type="text" name="query" class="search-bar" placeholder="Search properties..." value="{{ query }}">
                <button type="submit" class="submit-btn">Search</button>
            </div>
        </form>
    </div>
{% endif %}

<!-- Grid container for properties -->
<div class="grid-container">
    {% if latest_property_list %}
        {% for property in latest_property_list %}
            <a href="{% url 'bidder:detail' property.id %}" class="property-card">
                <div class="property-image-card">
                    <img src="{{ property.image.url }}" alt="{{ property.address }} image">
                </div>
                <div class="property-address">
                    {{ property.address }}
                </div>
            </a>
        {% endfor %}
    {% else %}
        <p>No properties are available.</p>
    {% endif %}
</div>
{% endblock %}

bidder/templates/bidder/login.html
{% extends "bidder/base.html" %}

{% block content %}
<div class="login-form-container">
    <form method="post" class="small-form">
        {% csrf_token %}
        <fieldset>
            <p>{{ form.username.label_tag }} {{ form.username }}</p>
            <p>{{ form.password.label_tag }} {{ form.password }}</p>
            <button type="submit" class="submit-btn">Login</button>
        </fieldset>
    </form>
</div>
{% endblock %}

bidder/templates/bidder/user.html
{% extends "bidder/base.html" %}

{% block content %}

<div class="search-container">
    <h3>User home coming soon... 🔨</h3>
</div>

{% endblock %}